/*
 * Copyright (c) 2026
 * Stephane D'Alu, Inria Chroma / Inria Agora, INSA Lyon, CITI Lab.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * The accepted values here are the same ones _dw1000_radio_is_valid()
 * enforces in dw1000.c, field for field, including the option guard on
 * the proprietary preamble lengths. That is a deliberate pairing and the
 * reason this file is worth having: a caller that writes its own table
 * gets it wrong, as the sniffer's did: it refused preamble codes 13..16
 * as "not supported in this implementation" when lde_repc_tunning covers
 * all of 1..24, refused 21..24 outright, and accepted every preamble
 * length whether the build had proprietary lengths or not.
 *
 * What is NOT here is anything about a combination of fields. Those rules
 * live in _dw1000_radio_is_valid() alone, and dw1000_configure() runs
 * them on every call.
 */

#include <dw1000/dw1000.h>
#include <dw1000/dw1000_validate.h>

/* Every function has the same shape: a switch that either writes the
 * encoded value or names a message, then one exit. Written out rather
 * than generated by a macro: the messages differ, which is most of the
 * value, and a table of them reads worse than this does.
 */

bool
dw1000_validate_channel(int channel, uint8_t *val, const char **errmsg)
{
    const char *msg = NULL;

    switch (channel) {
    case 1: case 2: case 3: case 4: case 5: case 7:
	if (val) *val = (uint8_t)channel;
	break;
    case 6:
	msg = "there is no channel 6 on the DW1000";
	break;
    default:
	msg = "channel must be 1, 2, 3, 4, 5 or 7";
	break;
    }

    if (errmsg) *errmsg = msg;
    return msg == NULL;
}


bool
dw1000_validate_bitrate(int kbps, uint8_t *val, const char **errmsg)
{
    const char *msg = NULL;

    switch (kbps) {
    case 6800:
	if (val) *val = DW1000_BITRATE_6800KBPS;
	break;
    case 850:
	if (val) *val = DW1000_BITRATE_850KBPS;
	break;
    case 110:
	if (val) *val = DW1000_BITRATE_110KBPS;
	break;
    default:
	msg = "bitrate must be 110, 850 or 6800 kbps";
	break;
    }

    if (errmsg) *errmsg = msg;
    return msg == NULL;
}


bool
dw1000_validate_prf(int mhz, uint8_t *val, const char **errmsg)
{
    const char *msg = NULL;

    switch (mhz) {
    case 16:
	if (val) *val = DW1000_PRF_16MHZ;
	break;
    case 64:
	if (val) *val = DW1000_PRF_64MHZ;
	break;
    case 4:
	/* DW1000_PRF_4MHZ exists in the API; the receiver does not
	 * support it and _dw1000_radio_is_valid() refuses it. Say which
	 * of the two it is, rather than "not a PRF". */
	msg = "a PRF of 4MHz is not supported by the DW1000 receiver";
	break;
    default:
	msg = "PRF must be 16 or 64 MHz";
	break;
    }

    if (errmsg) *errmsg = msg;
    return msg == NULL;
}


bool
dw1000_validate_pcode(int pcode, uint8_t *val, const char **errmsg)
{
    const char *msg = NULL;

    /* All of 1..24. lde_repc_tunning[] in dw1000.c has an entry for every
     * one of them, and _dw1000_radio_is_valid() accepts the same range.
     * Which ones go with which PRF is dw1000_configure()'s business. */
    if ((pcode >= 1) && (pcode <= 24)) {
	if (val) *val = (uint8_t)pcode;
    } else {
	msg = "preamble code must be 1 to 24";
    }

    if (errmsg) *errmsg = msg;
    return msg == NULL;
}


bool
dw1000_validate_plen(int symbols, uint8_t *val, const char **errmsg)
{
    const char *msg = NULL;

    switch (symbols) {
    case   64:
	if (val) *val = DW1000_PLEN_64;
	break;
    case 1024:
	if (val) *val = DW1000_PLEN_1024;
	break;
    case 4096:
	if (val) *val = DW1000_PLEN_4096;
	break;

    /* Proprietary, and gated exactly as _dw1000_radio_is_valid() gates
     * them: accepting one here in a build without the option would hand
     * the caller a value dw1000_configure() then refuses, which is the
     * worst of both: a validator that passes and a configure that
     * fails, with the message on the wrong side. */
    case  128: case  256: case  512:
    case 1536: case 2048:
#if DW1000_WITH_PROPRIETARY_PREAMBLE_LENGTH
	switch (symbols) {
	case  128: if (val) *val = DW1000_PLEN_128;  break;
	case  256: if (val) *val = DW1000_PLEN_256;  break;
	case  512: if (val) *val = DW1000_PLEN_512;  break;
	case 1536: if (val) *val = DW1000_PLEN_1536; break;
	case 2048: if (val) *val = DW1000_PLEN_2048; break;
	}
#else
	msg = "preamble lengths 128, 256, 512, 1536 and 2048 are"
	      " proprietary and this driver was compiled without"
	      " DW1000_WITH_PROPRIETARY_PREAMBLE_LENGTH";
#endif
	break;

    default:
#if DW1000_WITH_PROPRIETARY_PREAMBLE_LENGTH
	msg = "preamble length must be 64, 128, 256, 512, 1024, 1536,"
	      " 2048 or 4096 symbols";
#else
	msg = "preamble length must be 64, 1024 or 4096 symbols";
#endif
	break;
    }

    if (errmsg) *errmsg = msg;
    return msg == NULL;
}


bool
dw1000_validate_pac(int symbols, uint8_t *val, const char **errmsg)
{
    const char *msg = NULL;

    switch (symbols) {
    case  8:
	if (val) *val = DW1000_PAC8;
	break;
    case 16:
	if (val) *val = DW1000_PAC16;
	break;
    case 32:
	if (val) *val = DW1000_PAC32;
	break;
    case 64:
	if (val) *val = DW1000_PAC64;
	break;
    default:
	msg = "PAC size must be 8, 16, 32 or 64 symbols";
	break;
    }

    if (errmsg) *errmsg = msg;
    return msg == NULL;
}


bool
dw1000_validate_antenna_delay(double meters, uint16_t *val,
			      const char **errmsg)
{
    const char *msg   = NULL;
    double      ticks = DW1000_METER_TO_CLOCK(meters);

    /* The register field is sixteen bits (TX_ANTD, and the RX half of
     * LDE_RXANTD), so the ceiling is a property of the chip rather than a
     * policy: UINT16_MAX ticks is about 307 m of flight. */
    if (ticks < 0) {
	msg = "antenna delay cannot be negative";
    } else if (ticks > (double)UINT16_MAX) {
	msg = "antenna delay is too big for the 16-bit register"
	      " (the most it holds is about 307 m)";
    } else {
	if (val) *val = (uint16_t)ticks;
    }

    if (errmsg) *errmsg = msg;
    return msg == NULL;
}


/*
 * Local Variables:
 * c-basic-offset: 4
 * End:
 */
